### ISSUE TITLE
Eliminar comentarios.

### ISSUE THREAD

**Issue by Nidev-lab** [juandurso/backend-PastaSanaWEB#1]
Buenas! como va? encontre algunos comentarios en el codigo,

![image](https://github.com/juandurso/backend-PastaSanaWEB/assets/53904695/4b619b9e-90d1-47ec-a77e-981b4003117d)
Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by juandurso** [comment]
buenas noches, ya borre comentarios de codigo,  deje algunos comentarios que dicen que hace la funcion a la cual hace referencia. Si es necesario lo borro.
